project_name: ipscout

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy
builds:
  -
    id: macos-ipscout
    binary: ipscout
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"
    hooks:
      post:
        - |
          sh -c '
          cat > /tmp/ipscout_gon_arm64.hcl << EOF
          source = ["./dist/macos-ipscout_darwin_arm64/ipscout"]
          bundle_id = "uk.co.lessknown.ipscout"
          apple_id {
            username = "jon@lessknown.co.uk"
            provider = "VBZY8FBYR5"
          }
          sign {
            application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
          }
          zip {
            output_path = "./dist/ipscout_darwin_arm64.zip"
          }
          EOF
          gon -log-level=info -log-json /tmp/ipscout_gon_arm64.hcl
          echo $?
          '
          echo $?
        - |
          sh -c '
          cat > /tmp/ipscout_gon_amd64.hcl << EOF
          source = ["./dist/macos-ipscout_darwin_amd64_v1/ipscout"]
          bundle_id = "uk.co.lessknown.ipscout"
          apple_id {
            username = "jon@lessknown.co.uk"
            provider = "VBZY8FBYR5"
          }
          sign {
            application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
          }
          zip {
            output_path = "./dist/ipscout_darwin_amd64_v1.zip"
          }
          EOF
          echo $?
          gon -log-level=info -log-json /tmp/ipscout_gon_amd64.hcl
          echo $?
          '
  -
    id: ipscout
    binary: ipscout
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

brews:
  -
    name: ipscout
    homepage: 'https://github.com/jonhadfield/ipscout'
    description: 'A command line tool useful for network administrators and security analysts to quickly identify the origin and threat of an IP address.'
    repository:
      owner: jonhadfield
      name: homebrew-ipscout

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - macos-ipscout
      - ipscout
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

release:
  github:
    owner: jonhadfield
    name: ipscout
  prerelease: auto
  name_template: '{{ .Tag }}'
  extra_files:
    - glob: ./dist/ipscout_darwin*.zip

announce:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - README
      - test
      - ignore

checksum:
  name_template: 'checksums.txt'
#
#universal_binaries:
#  -
#    id: ipscout
#    replace: true

#notarize:
#  macos:
#    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
#      ids:
#        - ipscout
#      sign:
#        certificate: "{{.Env.MACOS_SIGN_P12}}"
#        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
#      notarize:
#        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
#        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
#        key: "{{.Env.MACOS_NOTARY_KEY}}"