version: 2

project_name: ipscout

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy

builds:
  - id: ipscout
    binary: ipscout
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - '-X github.com/jonhadfield/ipscout/helpers.Version={{ .Version }}_{{ .Date }}_UTC'
      - '-X github.com/jonhadfield/ipscout/helpers.SemVer={{ .Tag }}'

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds:
      - ipscout
    format_overrides:
      - goos: windows
        format: zip
    files:
      - license*
      - readme*
      - changelog*
      - none*

checksum:
  name_template: checksums.txt

release:
  github:
    owner: jonhadfield
    name: ipscout
  prerelease: auto
  name_template: "{{ .Tag }}"
  extra_files:
    - glob: ./dist/ipscout_darwin*.zip

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - README*
      - test
      - ignore

brews:
  - name: ipscout
    homepage: https://github.com/jonhadfield/ipscout
    description: >
      A command line tool for network administrators and security analysts to quickly identify the origin and threat of an IP address.
    repository:
      owner: jonhadfield
      name: homebrew-ipscout

announce:
  skip: true
