project_name: ipscout

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy
builds:
  -
    id: ipscout
    binary: ipscout
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

brews:
  -
    name: ipscout
    homepage: 'https://github.com/jonhadfield/ipscout'
    description: 'A command line tool for network administrators and security analysts to quickly identify the origin and threat of an IP address.'
    repository:
      owner: jonhadfield
      name: homebrew-ipscout

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - ipscout
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

release:
  github:
    owner: jonhadfield
    name: ipscout
  prerelease: auto
  name_template: '{{ .Tag }}'
  extra_files:
    - glob: ./dist/ipscout_darwin*.zip

announce:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - README
      - test
      - ignore

checksum:
  name_template: 'checksums.txt'