---
global:
    indent_spaces: 2
    max_value_chars: 300
    max_age: 90d
    # ports: [80]

providers:
    aws:
        enabled: true
    azure:
        enabled: true
    criminalip:
        enabled: true
        max_ports: 10
    digitalocean:
        enabled: true
    shodan:
        enabled: true
        max_ports: 10
