---
global:
    indent_spaces: 2
    max_value_chars: 300
    max_age: 90d
    # ports: [80]

providers:
    shodan:
        enabled: true
        max_ports: 10
        # ports: [80]
    criminalip:
        enabled: true
        max_ports: 10
    aws:
        enabled: true
    digitalocean:
        enabled: true
