---
global:
    indent-spaces: 2
    max-value-chars: 300
    # ports: [80]

providers:
    shodan:
        enabled: true
        max-ports: 10
        # ports: [80]
        no-older-than: 7d
    criminalip:
        enabled: true
        max-ports: 10
        no-older-than: 7d
    aws:
        enabled: true
    digitalocean:
        enabled: true
