---
global:
  indent_spaces: 2
  max_value_chars: 300
  max_age: 90d
  max_reports: 5
  output: table
  style: cyan
  # ports: [80]

providers:
  abuseipdb:
    enabled: true
  annotated:
    enabled: true
    paths:
    # - <path to yaml file>
  aws:
    enabled: true
  azure:
    enabled: true
  bingbot:
    enabled: true
  criminalip:
    enabled: true
  digitalocean:
    enabled: true
  gcp:
    enabled: true
  google:
    enabled: true
  googlebot:
    enabled: true
  icloudpr:
    # disabled by default as can slow down old processors
    enabled: false
  ipapi:
    enabled: true
  ipurl:
    enabled: true
    urls:
#      - "https://iplists.firehol.org/files/firehol_level1.netset"
#      - "https://iplists.firehol.org/files/firehol_level2.netset"
      - "https://iplists.firehol.org/files/blocklist_de.ipset"
      - "https://iplists.firehol.org/files/socks_proxy_7d.ipset"
      - "https://iplists.firehol.org/files/sslproxies_7d.ipset"
      - "https://iplists.firehol.org/files/tor_exits_7d.ipset"
  linode:
    enabled: true
  ptr:
    enabled: true
    nameservers:
      - 1.1.1.1
      - 9.9.9.9
  shodan:
    enabled: true
  virustotal:
    enabled: true
    show_providers: true
    show_unrated: true
    show_harmless: true
    show_clean: true