---
global:
  indent_spaces: 2
  max_value_chars: 300
  max_age: 90d
  max_reports: 5
  output: table
  style: cyan
  # ports: [80]

rating:
  config_path: <home>/.config/ratingConfig.json
  use-ai: false
  openai-api-key: <your-openai-api-key>

providers:
  abuseipdb:
    enabled: true
  alibaba:
    enabled: true
  annotated:
    enabled: true
    paths:
    # - <path to yaml file>
  aws:
    enabled: true
  azure:
    enabled: true
  azurewaf:
    enabled: false
    resource_ids:
      - /subscriptions/08796683-91d4-4205-9a41-826889f266e9/resourceGroups/example/providers/Microsoft.Network/frontdoorWebApplicationFirewallPolicies/example
  bingbot:
    enabled: true
  criminalip:
    enabled: true
  digitalocean:
    enabled: true
  gcp:
    enabled: true
  google:
    enabled: true
  googlebot:
    enabled: true
  googlesc:
    enabled: true
  hetzner:
    enabled: true
  icloudpr:
    # disabled by default as can slow down old processors
    enabled: false
  ipapi:
    enabled: true
  ipqs:
    enabled: true
  ipurl:
    enabled: true
    urls:
      - "http://lists.blocklist.de/lists/apache.txt"
      - "https://iplists.firehol.org/files/socks_proxy_1d.ipset"
      - "https://iplists.firehol.org/files/sslproxies_1d.ipset"
  #      - "http://lists.blocklist.de/lists/all.txt"
  #      - "https://iplists.firehol.org/files/firehol_level1.netset"
  #      - "https://iplists.firehol.org/files/firehol_level2.netset"
  #      - "https://iplists.firehol.org/files/tor_exits_7d.ipset"
  linode:
    enabled: true
  m247:
    enabled: true
  ovh:
    enabled: true
  ptr:
    enabled: true
    nameservers:
      - 1.1.1.1
      - 9.9.9.9
  shodan:
    enabled: true
  virustotal:
    enabled: true
    show_providers: true
    show_unrated: true
    show_harmless: true
    show_clean: true
  zscaler:
    enabled: true
